import {Platform, StyleSheet} from 'react-native';
import constants from '../constants';
import {
  BLUE,
  BORDER,
  DARK_GRAY,
  GREEN,
  RED,
  LIGHT_GRAY,
  WHITE,
  BLACK,
  GRAY,
  NIGHT,
} from '../constants/Colors';
import {ifIphoneX} from 'react-native-iphone-x-helper';

const HEIGHT = constants.BaseStyle.DEVICE_HEIGHT / 100;
const WIDTH = constants.BaseStyle.DEVICE_WIDTH / 100;

const CommonStyles = StyleSheet.create({
  //history
  OTPlineView: {
    borderBottomColor: BORDER,
    marginVertical: HEIGHT * 2,
    borderBottomWidth: StyleSheet.hairlineWidth,
    marginBottom: 30,
  },
  lineView: {
    borderBottomColor: BORDER,
    borderBottomWidth: StyleSheet.hairlineWidth,
    marginVertical: HEIGHT * 2,
  },
  lineOf2FAPin: {
    borderBottomColor: BORDER,
    borderBottomWidth: StyleSheet.hairlineWidth,
    marginVertical: HEIGHT * 2,
    width: 350,
    alignSelf: 'center',
  },
  lineViewNoMargin: {
    borderBottomColor: BORDER,
    borderBottomWidth: StyleSheet.hairlineWidth,
    marginVertical: HEIGHT,
  },
  smallDot: {
    height: 3,
    width: 3,
    borderRadius: 1.5,
    backgroundColor: DARK_GRAY,
  },
  tinyDot: {
    height: 2,
    width: 2,
    borderRadius: 1,
  },
  mediumDot: {
    height: 4,
    width: 4,
    borderRadius: 2,
    backgroundColor: DARK_GRAY,
  },
  mediumAuctionDot: {
    height: 8,
    width: 8,
    borderRadius: 4,
    backgroundColor: DARK_GRAY,
  },
  largeDot: {
    height: 12,
    width: 12,
    borderRadius: 6,
    backgroundColor: DARK_GRAY,
  },

  watchlistLineView: {
    borderBottomColor: BORDER,
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingBottom: HEIGHT * 1.5,
    marginBottom: HEIGHT * 0.03,
  },
  watchlistTopLineView: {
    borderBottomColor: BORDER,
    borderBottomWidth: StyleSheet.hairlineWidth,
    marginTop: HEIGHT * 2,
  },
  modalLineView: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    marginVertical: HEIGHT,
  },
  swapContainer: {
    paddingVertical: HEIGHT * 2,
    width: WIDTH * 100 - 40,
    borderRadius: 12,
    backgroundColor: NIGHT,
    shadowColor: '#B620E0',
    shadowOpacity: 1,
    shadowRadius: 50,
    alignSelf: 'center',
    marginTop: HEIGHT * 1,
  },

  selectTokenView: {
    paddingVertical: HEIGHT * 1,
    width: WIDTH * 100 - 10,
    borderRadius: 12,
    backgroundColor: NIGHT,
    shadowColor: '#B620E0',
    shadowOpacity: 1,
    shadowRadius: 50,
    alignSelf: 'center',
    marginTop: HEIGHT * 1,
  },

  TokenViewFlatlist: {
    flexDirection: 'row',
    marginHorizontal: 10,
  },
  TokenHeader: {
    backgroundColor: 'white',
    // width: '95%',
    flexDirection: 'row',
    padding: 9,
    // margin: 10,
    // justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 10,
    marginTop: HEIGHT * 10,
  },
  //dashboard
  dashBoardTabView: {
    borderColor: LIGHT_GRAY,
    backgroundColor: WHITE,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    marginHorizontal: WIDTH * 2,
    width: Platform.OS === 'ios' ? ifIphoneX(110, 110) : 110,
    height: 32,
    justifyContent: 'space-evenly',
  },
  dashBoardTabViewDark: {
    borderColor: WHITE,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    marginHorizontal: WIDTH * 2,
    width: Platform.OS === 'ios' ? ifIphoneX(110, 110) : 110,
    height: 32,
    justifyContent: 'space-evenly',
  },
  dashBoardSelectedTabView: {
    //borderColor: PURPLE,
    backgroundColor: WHITE,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    marginHorizontal: WIDTH * 2,
    width: Platform.OS === 'ios' ? ifIphoneX(110, 110) : 110,
    height: 32,
    justifyContent: 'space-evenly',
  },
  bottomUpBuyButton: {
    width: WIDTH * 80,
    height: HEIGHT * 6,
    borderRadius: HEIGHT * 3,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  dashBoardSelectedTabViewDark: {
    backgroundColor: WHITE,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    marginHorizontal: WIDTH * 2,
    width: Platform.OS === 'ios' ? ifIphoneX(110, 110) : 110,
    height: 32,
    justifyContent: 'space-evenly',
  },
  tabDashboardImage: {
    width: 16,
    height: 14,
  },
  brokerageAccountView: {
    backgroundColor: BLUE,
    borderRadius: 8,
    paddingHorizontal: WIDTH * 5,
    paddingVertical: HEIGHT * 2,
  },
  accountMenuView: {
    backgroundColor: BLUE,
    borderRadius: 8,
    paddingHorizontal: WIDTH * 5,
    paddingVertical: HEIGHT * 2,
  },
  accountVerificationView: {
    borderRadius: 6,
    paddingHorizontal: WIDTH * 3,
    paddingVertical: HEIGHT * 3,
    borderWidth: StyleSheet.hairlineWidth,
  },
  brokerageInfoView: {
    borderRadius: 6,
    paddingHorizontal: WIDTH * 3,
    paddingVertical: HEIGHT * 2,
    borderWidth: StyleSheet.hairlineWidth,
  },
  textWidth: {
    width: WIDTH * 60,
  },
  upArrowImage: {
    position: 'absolute',
    alignSelf: 'center',
    top: HEIGHT * 1.1,
    zIndex: 9999,
  },
  verticalDot: {
    height: 10,
    width: 4,
    borderRadius: 2,
    marginRight: 6,
  },
  chartView: {
    height: HEIGHT * 30,
    width: '100%',
    marginTop: HEIGHT * 2,
    alignSelf: 'center',
    marginBottom: HEIGHT * 5,
  },
  watchlistPriceView: {
    borderRadius: 6,
    alignItems: 'center',
    paddingVertical: HEIGHT * 0.8,
    minWidth: WIDTH * 22,
    paddingHorizontal: WIDTH,
  },
  verticalView: {
    height: 26,
    borderRightColor: LIGHT_GRAY,
    borderRightWidth: 1,
  },
  iconRowView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: 80,
    height: 26,
    borderRadius: 90,
    borderColor: LIGHT_GRAY,
    borderWidth: 1,
  },
  boxView: {
    borderRadius: 4,
    borderWidth: 1.5,
    width: WIDTH * 27,
    paddingVertical: HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  boxViewDark: {
    borderRadius: 4,
    borderWidth: 1.5,
    width: WIDTH * 27,
    paddingVertical: HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chartControlContentView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: WIDTH * 100 - 40,
  },
  selectedChartControlGreen: {
    height: 24,
    width: 36,
    borderWidth: 1,
    borderRadius: 6,
    borderColor: GREEN,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedChartControlRed: {
    height: 24,
    width: 36,
    borderWidth: 1,
    borderRadius: 6,
    borderColor: RED,
    backgroundColor: RED,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedChartControl: {
    height: 24,
    width: 36,
    borderWidth: 1,
    borderRadius: 6,
    borderColor: WHITE,
    backgroundColor: WHITE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedChartControlDark: {
    height: 24,
    width: 36,
    borderWidth: 1,
    borderRadius: 6,
    borderColor: BLACK,
    backgroundColor: BLACK,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // stock position
  amountView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: HEIGHT,
  },
  amountStatusView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stockChartView: {
    height: HEIGHT * 35,
    width: '100%',
    marginTop: HEIGHT * 3,
  },
  sparkChartView: {
    height: HEIGHT * 4,
    width: WIDTH * 15,
  },
  newsImageView: {
    height: HEIGHT * 12,
    width: HEIGHT * 12,
    borderRadius: 6,
    // borderWidth: StyleSheet.hairlineWidth,
    // borderColor: GRAY,
  },
  newsPublisherView: {
    width: 50,
    height: 20,
    resizeMode: 'contain',
    marginBottom: 10,
  },
  newsItem: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: LIGHT_GRAY,
    borderRadius: 12,
  },
  modalView: {
    position: 'absolute',
    bottom: 0,
    width: WIDTH * 100,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: WIDTH * 5,
    paddingTop: HEIGHT,
    paddingBottom: HEIGHT * 6,
  },
  modalNumericView: {
    position: 'absolute',
    bottom: 0,
    width: WIDTH * 100,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: WIDTH * 5,
    paddingTop: HEIGHT,
    paddingBottom: HEIGHT * 4,
  },
  modalTopLine: {
    height: HEIGHT * 0.5,
    width: WIDTH * 12,
    borderRadius: 10,
    alignSelf: 'center',
    marginVertical: HEIGHT,
  },
  bottomBuyButton: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: BLUE,
    width: WIDTH * 100,
    height: HEIGHT * 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomWatchlistSearchButton: {
    width: WIDTH * 20,
    height: WIDTH * 10,
    borderWidth: 1,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brokerageAccountButton: {
    //paddingHorizontal: WIDTH * 2,
    paddingVertical: WIDTH * 3,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewButton: {
    position: 'relative',
    bottom: 0,
    backgroundColor: BLUE,
    width: WIDTH * 100,
    height: HEIGHT * 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  copyButton: {
    width: 126,
    height: 44,
    borderWidth: 1,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 20,
  },
  nftCopyButton: {
    width: WIDTH * 20,
    height: WIDTH * 10,
    borderWidth: 1,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  nftFilterButton: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    height: 50,
    paddingHorizontal: 20,
    borderRadius: 25,
    marginBottom: 30,
  },
  createAlertButton: {
    backgroundColor: 'rgba(0, 171, 89, 0.1)',
    paddingHorizontal: 30,
    height: 44,
    borderWidth: 1,
    borderRadius: 22,
    borderColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 10,
    marginTop: 20,
  },

  inputField: {
    // borderRadius: 4,
    // borderColor: WHITE,
    height: HEIGHT,
    // width: WIDTH * 30,
    width: WIDTH * 20,
  },
  textInput: {
    width: WIDTH * 20,
  },

  // Order status

  viewOrderText: {
    position: 'absolute',
    bottom: HEIGHT * 11,
    alignSelf: 'center',
  },

  historyFilterContainer: {
    paddingVertical: HEIGHT * 0.5,
    paddingHorizontal: WIDTH * 4,
    borderRadius: 20,
    marginRight: WIDTH * 2,
    borderWidth: 1,
    borderColor: LIGHT_GRAY,
  },
  historyFilterContainerDark: {
    paddingVertical: HEIGHT * 0.5,
    paddingHorizontal: WIDTH * 4,
    borderRadius: 20,
    marginRight: WIDTH * 2,
    borderWidth: 1,
    borderColor: WHITE,
  },
  selectedHistoryFilterContainer: {
    paddingVertical: HEIGHT * 0.5,
    paddingHorizontal: WIDTH * 4,
    borderRadius: 20,
    marginRight: WIDTH * 2,
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: BLACK,
  },
  selectedHistoryFilterContainerDark: {
    paddingVertical: HEIGHT * 0.5,
    paddingHorizontal: WIDTH * 4,
    borderRadius: 20,
    marginRight: WIDTH * 2,
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: WHITE,
  },
  NFTContainer: {
    paddingVertical: HEIGHT,
    paddingHorizontal: WIDTH * 2,
    borderRadius: 8,
    marginRight: WIDTH * 2,
    borderWidth: 1,
    borderColor: LIGHT_GRAY,
  },
  NFTContainerDark: {
    paddingVertical: HEIGHT,
    paddingHorizontal: WIDTH * 2,
    borderRadius: 8,
    marginRight: WIDTH * 2,
    borderWidth: 1,
    borderColor: WHITE,
  },
  selectedNFTFilterContainer: {
    paddingVertical: HEIGHT,
    paddingHorizontal: WIDTH * 2,
    borderRadius: 8,
    marginRight: WIDTH * 2,
    borderWidth: 1,
    borderColor: BLACK,
  },
  selectedNFTFilterContainerDark: {
    paddingVertical: HEIGHT,
    paddingHorizontal: WIDTH * 2,
    borderRadius: 8,
    marginRight: WIDTH * 2,
    borderWidth: 1,
    borderColor: WHITE,
  },
  NFTFilterMenu: {
    height: WIDTH * 30,
    width: WIDTH * 30,
    borderRadius: 8,
    marginRight: WIDTH * 3,
    padding: 15,
    borderWidth: 1.5,
  },
  NFTFeaturesContainer: {
    paddingVertical: HEIGHT,
    paddingHorizontal: WIDTH * 2,
    borderRadius: 8,
    marginRight: WIDTH * 2,
    borderWidth: 1,
  },
  nftHeaderIconContainer: {
    height: 30,
    width: 30,
    borderRadius: 15,
    borderColor: BLACK,
  },
  nftHeaderIconContainerDark: {
    height: 30,
    width: 30,
    borderRadius: 15,
  },
  priceCutContainer: {
    height: HEIGHT * 4,
    paddingHorizontal: WIDTH * 2,
    borderRadius: HEIGHT * 2,
    borderWidth: 1,
    borderColor: BLACK,
    alignItems: 'center',
    justifyContent: 'center',
  },
  priceCutContainerDark: {
    height: HEIGHT * 4,
    paddingHorizontal: WIDTH * 2,
    borderRadius: HEIGHT * 2,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: WHITE,
  },
  nftCheckoutImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    alignSelf: 'center',
  },
  nftNewListings: {
    marginRight: WIDTH * 2,
    alignContent: 'center',
  },
  newNFTImage: {
    width: 300,
    height: 300,
    resizeMode: 'contain',
    borderRadius: 4,
    borderColor: BORDER,
    borderWidth: StyleSheet.hairlineWidth,
  },
  nftImageHeader: {
    zIndex: 999,
    position: 'absolute',
    marginTop: 0,
    width: WIDTH * 100,
    paddingTop: 55,
  },
  nftSendFee: {
    width: WIDTH * 100 - 40,
    borderRadius: 4,
    borderWidth: 1,
    padding: 15,
  },
  trendingImage: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
    borderRadius: 4,
    borderColor: BORDER,
    borderWidth: StyleSheet.hairlineWidth,
    marginRight: WIDTH * 2,
  },
  nftCoverImage: {
    width: WIDTH * 100,
    height: WIDTH * 100,
    resizeMode: 'contain',
    borderColor: BORDER,
    borderWidth: StyleSheet.hairlineWidth,
  },
  nftDetailsImage: {
    width: WIDTH * 100,
    height: WIDTH * 100,
    resizeMode: 'contain',
  },
  ethereumIconImage: {
    width: WIDTH * 8,
    height: WIDTH * 8,
    resizeMode: 'contain',
  },
  sellingCardImage: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderColor: BORDER,
    borderWidth: StyleSheet.hairlineWidth,
    marginRight: WIDTH * 2,
  },
  galleryImage: {
    width: (WIDTH * 100) / 2 - 15,
    height: (WIDTH * 100) / 2 - 15,
    resizeMode: 'contain',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderColor: BORDER,
    borderWidth: StyleSheet.hairlineWidth,
  },
  galleryNoImage: {
    width: (WIDTH * 100) / 2 - 16,
    height: (WIDTH * 100) / 2 - 15,
    resizeMode: 'contain',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderColor: BORDER,
    borderWidth: StyleSheet.hairlineWidth,
  },
  galleryCard: {
    width: (WIDTH * 100) / 2 - 15,
    height: (WIDTH * 100) / 2 + 30,
    resizeMode: 'contain',
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    marginBottom: WIDTH * 2,
  },
  receiveNFTImage: {
    width: WIDTH * 100 - 100,
    height: WIDTH * 100 - 100,
    //resizeMode: 'contain',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderColor: BORDER,
    borderWidth: StyleSheet.hairlineWidth,
  },
  receiveNFTCard: {
    width: WIDTH * 100 - 100,
    height: WIDTH * 100 + 165,
    resizeMode: 'contain',
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
  },
  receiveETHCard: {
    width: WIDTH * 100 - 40,
    padding: 20,
    resizeMode: 'contain',
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
  },
  sellingCard: {
    width: 200,
    height: 325,
    resizeMode: 'contain',
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    marginRight: WIDTH * 2,
  },
  nftCard: {
    width: (WIDTH * 100) / 2 - 25,
    height: 64,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    justifyContent: 'center',
  },
  nftCardFull: {
    width: WIDTH * 100 - 40,
    height: 80,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    justifyContent: 'center',
  },
  topSales: {
    width: 80,
    height: 80,
    resizeMode: 'contain',
    borderRadius: 4,
    borderColor: BORDER,
    borderWidth: StyleSheet.hairlineWidth,
    marginRight: WIDTH * 2,
  },
  filterImages: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
    borderRadius: 4,
    borderColor: BORDER,
    borderWidth: StyleSheet.hairlineWidth,
    marginRight: WIDTH * 2,
  },
  StockSearchHead: {
    paddingVertical: HEIGHT * 1,
    paddingHorizontal: WIDTH * 5,
    marginRight: WIDTH * 3,
  },
  alertItemContainer: {
    paddingVertical: HEIGHT * 0.2,
    paddingHorizontal: WIDTH * 3,
    borderRadius: 20,
    marginRight: WIDTH * 2,
    borderWidth: 1,
  },
  alertItemLayout: {
    marginVertical: HEIGHT * 0.25,
  },
  alertItemContainerRed: {
    paddingVertical: HEIGHT * 0.5,
    paddingHorizontal: WIDTH * 3,
    borderRadius: 20,
    marginRight: WIDTH * 2,
    borderWidth: 1,
    borderColor: RED,
  },
  leverageContainer: {
    paddingVertical: HEIGHT * 0.4,
    paddingLeft: 5,
    paddingRight: 8,
    borderRadius: 20,
    alignItems: 'center',
    flexDirection: 'row',
    alignSelf: 'flex-start',
  },
  selectedAlertItemContainer: {
    paddingVertical: HEIGHT * 0.5,
    paddingHorizontal: WIDTH * 3,
    borderRadius: 20,
    marginRight: WIDTH * 2,
    backgroundColor: 'rgba(64,100,253,0.1)',
    borderWidth: 1,
    borderColor: BLUE,
  },

  searchContainer: {
    backgroundColor: 'rgba(237,237,237,0.5)',
    height: 40,
    borderRadius: 20,
  },
  searchContainerDark: {
    backgroundColor: '#1F2124',
    height: 40,
    borderRadius: 20,
  },
  searchScreenCards: {
    width: WIDTH * 38,
    height: HEIGHT * 20,
    marginRight: 10,
    borderWidth: 1,
    borderRadius: 10,
  },
  textInputContainerStyle: {
    marginHorizontal: 10,
  },
  nftSearchTextInputContainerStyle: {
    marginLeft: 10,
    width: WIDTH * 100 - 100,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    borderBottomWidth: StyleSheet.hairlineWidth,
    justifyContent: 'space-between',
    width: WIDTH * 100 - 40,
  },
  accountMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    justifyContent: 'space-between',
    width: WIDTH * 100,
    paddingHorizontal: 20,
  },
  menuItemBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    width: WIDTH * 100 - 40,
    marginLeft: 20,
  },
  hairLine: {
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    width: WIDTH * 100 - 40,
  },
  menuItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  alertItemView: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: LIGHT_GRAY,
    borderRadius: 12,
    //paddingHorizontal: 12,
    paddingBottom: 12,
    marginRight: 15,
  },
  deleteBox: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    height: '100%',
    backgroundColor: RED,
  },
  onActive: {
    transform: [{scale: 1}],
    shadowColor: BLACK,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,

    elevation: 7,
  },
  top: {
    top: 30,
  },
  buttonContainer: {
    flexDirection: 'row',
    marginTop: 10,
    justifyContent: 'space-between',
  },
  blurBottom: {
    height: 100,
    width: WIDTH * 100,
    paddingHorizontal: 20,
  },

  scanIcon: {
    height: 20,
    width: 20,
    position: 'absolute',
    top: 10,
    left: WIDTH * 82,
  },
});
export default CommonStyles;
